# Obsoleta a partir docker compose V1.27.x
#version: '2.2'
services:
  node:
    container_name: node
    image: node:alpine
    # command: 'yarn dev'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - $PWD:/root/express
    working_dir: /root/express
    networks:
      - net
networks:
  net:
